### ISSUE TITLE
Symfony 6.4 - Method not found

### ISSUE THREAD

**Issue by phtmgt** [timiki/rpc-server-bundle#27]
These are my configs:

```
rpc:
    path: /rpc
    defaults: { _controller: Timiki\Bundle\RpcServerBundle\Controller\RpcController::handlerAction }
    methods: [ POST ]

```

```
# Read the documentation: https://github.com/timiki/rpc-server-bundle

rpc_server:

    mapping: '%kernel.project_dir%/src/Method'

    # id cache service, must be instanced of Psr\Cache\CacheItemPoolInterface
    # by default use file cache

    cache: null

    # id serializer service, must be instanced of Timiki\Bundle\RpcServerBundle\Serializer\SerializerInterface
    # by default use 'rpc.server.serializer.base' service

    serializer: null
```

And, this is my Method (which is properly parsed, as removing the ignore in services produces a 'duplicate' error):

```
<?php

declare(strict_types=1);

use Timiki\Bundle\RpcServerBundle\Attribute as RPC;
use Symfony\Component\Validator\Constraints as Assert;

#[RPC\Method("test")]
#[RPC\Roles(["ROLE_USER"])]
#[RPC\Cache(3600)]
class TestMethod
{
    #[RPC\Param]
    #[Assert\NotBlank]
    protected $param;

    #[RPC\Execute]
    public function execute()
    {
        $param = $this->param;

        $result = "Hello, World!";

        return $result;
    }
}
<?php

declare(strict_types=1);

use Timiki\Bundle\RpcServerBundle\Attribute as RPC;
use Symfony\Component\Validator\Constraints as Assert;

#[RPC\Method("test")]
#[RPC\Roles(["ROLE_USER"])]
#[RPC\Cache(3600)]
class TestMethod
{
    #[RPC\Param]
    #[Assert\NotBlank]
    protected $param;

    #[RPC\Execute]
    public function execute()
    {
        $param = $this->param;

        $result = "Hello, World!";

        return $result;
    }
}

```

Request:

```
{
  "jsonrpc": "2.0",
  "method": "test",
  "id": 1
}
```

Response:

```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32601,
    "message": "Method not found",
    "data": "test"
  },
  "id": 1
}
```

Am I missing something? Went over the instructions and my files 5 times already, cleared all kinds of cache.
